### ISSUE TITLE
User events stream

### ISSUE THREAD

**Issue by j3k0** [j3k0/ganomede-users#15]
* [x] specified events here: https://github.com/j3k0/ganomede-users/blob/feature/events/doc/events.md
 * [x] implement using ganomede-events's provided library
 * [x] extend events https://github.com/j3k0/ganomede-mailchimp-worker/issues/1#issuecomment-285104820
    * [x] this also requires extending the POST /accounts request to add initial usermeta

See https://github.com/j3k0/ganomede-events

**Comment by elmigranto** [comment]
Judging by https://github.com/j3k0/ganomede-usermeta/issues/7 we already write metas, just need to extend event with relevant stuff and unset `newsletter` in case email is missing (#32)?

**Comment by j3k0** [comment]
If I'm right it's already done, I'll check.

**Comment by j3k0** [comment]
Yes, initial metadata is set (https://github.com/j3k0/ganomede-users/blob/develop/src/users-api.coffee#L86-L96) and sent with the `CREATE` event: https://github.com/j3k0/ganomede-users/blob/develop/src/users-api.coffee#L95
