### ISSUE TITLE
Banning users: HTTP 405

### ISSUE THREAD

**Issue by j3k0** [j3k0/ganomede-users#40]
Banning users stopped working after upgrading to ganomede-users:v1.6.16

```
Upstream(http://BASE_URL/users/v1) failed HTTP 405: Method Not Allowed
{ options:
   { method: 'post',
     url: 'http://BASE_URL/users/v1/banned-users',
     body:
      { apiSecret: 'API_SECRET',
        username: 'USERNAME' },
     json: true },
  body:
   { code: 'MethodNotAllowedError',
     message: 'POST is not allowed' } }
```

**Comment by j3k0** [comment]
Let's check 48c8e3f8

**Comment by j3k0** [comment]
From ganomede-users logs:
```json
{"name":"users","hostname":"291ab3d4636a","pid":3729,"level":30,"req_id":"54fe5a5d-7d66-4f03-9d92-63a5e051c546","msg":"POST /users/v1/banned-users","time":"2017-07-03T10:22:54.287Z","v":0}
{"name":"users","hostname":"291ab3d4636a","pid":3729,"module":"usermeta","level":50,"err":{"jse_shortmsg":"","jse_info":{},"message":"POST is not allowed","statusCode":405,"body":{"code":"MethodNotAllowedError","message":"POST is not allowed"},"restCode":"MethodNotAllowedError","name":"MethodNotAllowedError"},"url":{"protocol":"https:","slashes":true,"auth":null,"host":"ACCOUNT_HOST","port":"443","hostname":"ACCOUNT_HOST","hash":null,"search":null,"query":null,"pathname":"/usermeta/v1","path":"/usermeta/v1","href":"https://ACCOUNT_HOST:443/usermeta/v1"},"options":{"path":"/usermeta/v1/USERNAME/$banned"},"body":{"code":"MethodNotAllowedError","message":"POST is not allowed"},"msg":"GanomedeUsermeta.post failed","time":"2017-07-03T10:22:54.354Z","v":0}
```

**Comment by j3k0** [comment]
`ganomede-usermeta` has `$banned` configured as a private metadata.

**Comment by elmigranto** [comment]
There is still a problem with unbanning. Seems that `users` tries to set key to `null`, however, `usermeta` only accepts strings. So we should probably update it to something else. Since we do not allow deletes in usermeta, we should go for one of the following:

 - use `'yes'` or `'no'` as values for `$banned` key (missing means `'no'`);
 - implement `usermeta` deletes and use that.

I'd go for first option, since only single place (`users`) changes. What do you think?

**Comment by elmigranto** [comment]
Actually… `$banned` is set to `String(Date.now())` when banning user. Timestamp for banned vs string `'no'` or missing key when user isn't. Feels wierd, though, but probably okay since this is behind http service? 🤷‍♂️

**Comment by elmigranto** [comment]
Ref #44 @j3k0
